services:
  app-backend:
    build:
      context: /opt/miniapp/app-backend
    container_name: miniapp-backend
    restart: unless-stopped
    environment:
      SERVER_PORT: "8080"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_USERNAME: "${TELEGRAM_USERNAME:-MiniAppBot}"
      APP_FRONTEND_URL: "${APP_FRONTEND_URL}"
      APP_START_TEXT: "${APP_START_TEXT:-Привет! Открой мини-приложение по кнопке ниже.}"
    ports:
      - "8081:8080"

  app-frontend:
    build:
      context: /opt/miniapp/app-frontend
    container_name: miniapp-frontend
    restart: unless-stopped
    ports:
      - "8082:80"
